### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by genericmoniker** [tmciver/out-of-the-tar-pit-epub#3]
I was excited to see your .epub, but Google Play Books said it couldn't process it when I tried adding it to my library. Running the validator at http://validator.idpf.org/ against the .epub produced by make revealed numerous errors, so maybe one of those was fatal so far as Google is concerned.

**Comment by bencochran** [comment]
I’m guessing you hit the same errors that I did. I have a proposed fix here: https://github.com/tmciver/out-of-the-tar-pit-epub/pull/2

**Comment by tmciver** [comment]
I merged @bencochran's PR which I verified fixes errors reported by iBooks but epubcheck (version 4.0.1) still reports some problems which I'll try to fix soon.  Stay tuned!
